//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KimdolSoft.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kimdolsoftEntities : DbContext
    {
        public kimdolsoftEntities()
            : base("name=kimdolsoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<contacto> contacto { get; set; }
        public virtual DbSet<cuentausuario> cuentausuario { get; set; }
        public virtual DbSet<detallecompra> detallecompra { get; set; }
        public virtual DbSet<detalledevolucion> detalledevolucion { get; set; }
        public virtual DbSet<detallemovimiento> detallemovimiento { get; set; }
        public virtual DbSet<devolucion> devolucion { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<existencia> existencia { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<movimiento> movimiento { get; set; }
        public virtual DbSet<presentacion> presentacion { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipomovimiento> tipomovimiento { get; set; }
        public virtual DbSet<tipoproducto> tipoproducto { get; set; }
        public virtual DbSet<unidad> unidad { get; set; }
    }
}
